### ISSUE TITLE
Selfish output

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/selfish#11]
Hi,
  when I took a look at the Selfish output, the last column is the fold change, but the third is the q value. It is odd that the fold change is 0, while qvalue is less than 0.05. What do you think?

![image](https://user-images.githubusercontent.com/12387462/85443345-25dd4480-b55f-11ea-912c-4adca18cc62b.png)

**Comment by ay-lab** [comment]
I think that is the case when the (i,j) interaction is zero in one of the contact maps. Can you check that interaction in your contact maps?

**Comment by BenxiaHu** [comment]
can I remove the rows when fold change equals to 0?
I also want to make sure that third column is q value, nor p value, right?

**Comment by ay-lab** [comment]
We are providing q-value for interactions that are zero in one of the contact maps and not zero in the other. If you are not interested in such interactions you can simply ignore/remove them. Yes, the third column is q-val.

**Comment by biozzq** [comment]
Dear @ay-lab 

I found that the header of the tsvout is labelled as `P_VAL`, but not q-value. Hope you can help me to confirm it.
`LOC1    LOC2    P_VAL   LOG_FOLD_CHANGE` 

Best wishes,
Zheng zhuqing

**Comment by ay-lab** [comment]
Hi Zheng, it's q-value.

**Comment by biozzq** [comment]
Dear @ay-lab 

Thank you. To make the header of tsvout more intuitive, it's better to modify your following code, including LOC1, LOC2, P_VAL (I understand if you don't want to change).
```
if tsvout:
        indices = np.argwhere(o < tsvout)
        with open(args.outdir, 'w') as outfile:
            outfile.write('LOC1\tLOC2\tP_VAL\tLOG_FOLD_CHANGE\n')
            for i in indices:
                _x, _y = i[0], i[1]
```
Best wishes,
Zheng Zhuqing
