### ISSUE TITLE
Selfish for 10kb

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/selfish#12]
Hi,
   I am trying to call differential interacting structures for 10kb matrix.
   can I use the default parameters for sigmaZero and Iteration?

-sz | --sigmaZero | Sigma0 parameter for Selfish. Default is experimentally chosen for 5Kb resolution.
-- | -- | --
-i | --iterations | Iteration count parameter for Selfish. Default is experimentally chosen for 5Kb resolution.
 
If not, do you have any suggestions?
Best,

**Comment by ay-lab** [comment]
Yes, default parameters work fine for most resolutions. Also, if you are more interested in interactions within a few Mb distance I suggest you limit the distance using -d parameter.

**Comment by BenxiaHu** [comment]
Thanks.
  Now I got 3380525 differential interacting regions. I am not sure whether it it true. How can I control the number of differential interacting regions?

**Comment by ay-lab** [comment]
By changing the q-val threshold (-t)  and limiting the distance (-d).
