### ISSUE TITLE
Selfish biasefile

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/selfish#13]
Hi,
  Can I use the biase file generated by HiC-Pro?

-b1 | --biases1 | Location of bias/normalization vector file for contact map 1. (See below for format.)
-- | -- | --
-b2 | --biases2 | Location of bias/normalization vector file for contact map 2. (See below for format.)

Best,

**Comment by ay-lab** [comment]
Yes, just make sure you use the right input format (explained in the README page).
