### ISSUE TITLE
how to deal with genes with multiple log2(FC)

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/selfish#14]
Hi,
   I still have 2 questions:
   1. the foldchange is the log2((A+1)/(b+1)), right?
   
  2. I used gene promoters to overlap with differential interacting regions. However, A lot of genes have multiple log2(FC). How to deal with this issue? 

![image](https://user-images.githubusercontent.com/12387462/86180228-b389d880-baf9-11ea-9645-a3792bb2c077.png)

Best,

**Comment by ay-lab** [comment]
Yes, it's the log-fold change between the two contact maps at that particular (i,j) bin. So, in fact there are two types of differences for each pixel: 1) Fold change which is simply calculated by the formula you mentioned above (note that a and b are KR-normalized contact maps) and 2) the significance of the difference (q-value) that selfish is computing. 

I am not exactly sure about what you mean by getting multiple fold-changes (or q-values), but note that:
1) A promoter can overlap multiple bins and/or 
2) the promoter bin (locus) can be involved in multiple differential interactions (for example DCIs={(i,j),(i,j+1),(i,j-1),...}).

**Comment by BenxiaHu** [comment]
yes. I used gene promoters to overlap with DCIs, leading to one gene promoter overlapping with multiple DCIs. So is there any way to aggregate the multiple DCIs(Fold change).

**Comment by ay-lab** [comment]
i) If the corresponding DCIs for a promoter are adjacent 2D pixels you can assume they are showing one interaction and maybe you can 1) run selfish in lower resolution or 2) do some sort of averaging.
ii) If the corresponding DCIs are not adjacent then they are showing different interactions and you shouldn't aggregate them (for example the promoter (x =500,000) is interacting with x=1,000,000 and also with 2,000,000 loci)!
