### ISSUE TITLE
how to convert selfish output to .hic format

### ISSUE THREAD

**Issue by BenxiaHu** [ay-lab/selfish#15]
Hi,
   I want to visualize the selfish output in Juicebox which requires the format of input file is .hic.
   Do you know how to convert the Selfish output to .hic format?
Best,

**Comment by ay-lab** [comment]
To show the differential interactions in juicebox you just need to import them as 2d annotations (view>show annotation panel>2d annotations) for the Hi-C contact map data you have. The input (for annotation) to juiceboox should have the format [chr1  start1  end1  chr2  start2  end2  q-val]. So in short, juicebox shows differential interactions on the contact map as annotations (black squares).

**Comment by BenxiaHu** [comment]
Thanks a lot.
But I have another question: https://github.com/ay-lab/selfish/issues/14#issue-648517508
